// Chat Action Types
export const SET_CHATS = "SET_CHATS";
export const ADD_CHAT = "ADD_CHAT";
export const UPDATE_CHAT_LAST_MESSAGE = "UPDATE_CHAT_LAST_MESSAGE";
export const UPDATE_CHAT_ONLINE_STATUS = "UPDATE_CHAT_ONLINE_STATUS";
export const SET_CHATS_LOADING = "SET_CHATS_LOADING";
export const SET_CHATS_ERROR = "SET_CHATS_ERROR";
export const CLEAR_CHATS = "CLEAR_CHATS";
export const INCREMENT_UNREAD_COUNT = "INCREMENT_UNREAD_COUNT";
export const RESET_UNREAD_COUNT = "RESET_UNREAD_COUNT";
