export const ADD_NOTIFICATION = "ADD_NOTIFICATION";


export const MARK_AS_READ = "MARK_AS_READ";


export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";


export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";


export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";


export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";